### ISSUE TITLE
Get portal-link not working from org admin ui

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-ui#5]
```
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 2022-10-10 18:02:10,318 INFO  [io.phasetwo.service.resource.OrganizationResource] (executor-thread-47) requesting portal-link for user , org 6954b712-5d46-4b23-b32a-41ab6130bf49
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 2022-10-10 18:02:10,375 WARN  [io.phasetwo.service.resource.OrganizationResource] (executor-thread-47) Error creating portal link: javax.ws.rs.NotAuthorizedException: HTTP 401 Unauthorized
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.phasetwo.service.resource.OrganizationResource.getPortalLink(OrganizationResource.java:206)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/java.lang.Thread.run(Thread.java:829)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 2022-10-10 18:02:10,376 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (executor-thread-47) MediaType not set on path /auth/realms/testerdo/orgs/6954b712-5d46-4b23-b32a-41ab6130bf49/portal-link, with response status 500
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 2022-10-10 18:02:10,376 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-47) Uncaught server error: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:75)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:40)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:361)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:380)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:358)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:201)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$1(QuarkusRequestFilter.java:90)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2022-10-10T20:02:10+02:00] (web/web/0d0d30989e634bbbad4f2e6bf615aefc) 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by xgp** [comment]
Updated to fix the form post.
